- name: lab_3 
  hosts: All
  vars:
      package_name: nginx
      package_version: latest
      path:
       - "file.css"
       - "file.js"   
      main_file: "index.html"       
  tasks:
      
    - name:  install nginx
      apt:
        name: "{{ package_name }}"
        state: "{{ package_version }}"
      notify: copy_files 

    - name: copy main file
      copy:
         src: "{{ main_file }}"
         dest: "/var/www/html"
      notify: restart nginx  


  handlers:

    - name: copy_files
      template:
         src: "{{ item }}"
         dest: "/var/www/html"
      loop: "{{ path }}"    
      notify: restart nginx

    - name: restart nginx
      service:
         name: "{{ package_name }}" 
         state: restarted

